// <auto-generated />
namespace Beardslee.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddBeardsleeWebistesandGiftCardCartsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBeardsleeWebistesandGiftCardCartsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201705270005388_Add-Beardslee-Webistes-and-GiftCardCarts-Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
